### ISSUE TITLE
IBM MQ metrics are ingested into New Relic but seeing MQJE001 errors in the log file

### ISSUE THREAD

**Issue by sri-shetty** [newrelic-experimental/newrelic-ibm-mq-monitor#2]
**## Environment**
IBM MQ running in the Mainframe, it is being remotely monitored. MQ metrics are coming over to New Relic but seeing following errors in the log file. 

**## Request**
Requesting to add additional debug statements or provide more meaningful error messages and advise on how to resolve. If these errors expected and won't impact the metrics collection, capture and handle exceptions in the code.

**## Error MQJE001: Completion Code '2', Reason '3007'**
at java.lang.Thread.run(Thread.java:822)
2021-08-17 11:33:16 [pool-2-thread-1] ERROR c.n.i.ibmmq.ListenerMetricCollector - Error fetching listener status for CSQD
com.ibm.mq.headers.pcf.PCFException: MQJE001: Completion Code '2', Reason '3007'.
        at com.ibm.mq.headers.pcf.PCFMessageAgent.send(PCFMessageAgent.java:321)
        at com.newrelic.infra.ibmmq.ListenerMetricCollector.reportListenerStatus(ListenerMetricCollector.java:46)
        at com.newrelic.infra.ibmmq.MQAgent.populateMetrics(MQAgent.java:100)
        at com.newrelic.infra.publish.insights.InsightsRunner$PollAgentsRunnable.run(InsightsRunner.java:161)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:319)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:191)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:822)

**## Error MQJE001: Completion Code '2', Reason '3015'**
2021-08-17 11:33:39 [pool-2-thread-1] ERROR c.n.i.ibmmq.QueueMetricCollector - Exception occurred
com.ibm.mq.headers.pcf.PCFException: MQJE001: Completion Code '2', Reason '3015'.
        at com.ibm.mq.headers.pcf.PCFMessage.getStringParameterValue(PCFMessage.java:760)
        at com.newrelic.infra.ibmmq.QueueMetricCollector.reportQueueStats(QueueMetricCollector.java:65)
        at com.newrelic.infra.ibmmq.MQAgent.populateMetrics(MQAgent.java:103)
        at com.newrelic.infra.publish.insights.InsightsRunner$PollAgentsRunnable.run(InsightsRunner.java:161)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:319)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:191)

**## Error MQJE001: Completion Code '2', Reason '2085'**
2021-07-15 11:59:56 [pool-2-thread-1] ERROR c.n.i.ibmmq.QueueMetricCollector - Exception occurred
com.ibm.mq.headers.pcf.PCFException: MQJE001: Completion Code '2', Reason '2085'.
       at com.ibm.mq.headers.pcf.PCFMessageAgent.send(PCFMessageAgent.java:313)
       at com.newrelic.infra.ibmmq.QueueMetricCollector.addResetQueueStats(QueueMetricCollector.java:111)
       at com.newrelic.infra.ibmmq.MQAgent.populateMetrics(MQAgent.java:104)
       at com.newrelic.infra.publish.insights.InsightsRunner$PollAgentsRunnable.run(InsightsRunner.java:161)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:319)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:
191)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
       at java.lang.Thread.run(Thread.java:822)

**Comment by adiosspandit** [comment]
@hsinghkalsi @psomareddy Would it be OK to add a config parameter to optionally ignore certain or all exceptions of type PCFException.

**Comment by psomareddy** [comment]
totally okay. if the configuration is too disprutive, consider creating a new branch for mainframe etc. and keep changes localized to that branch @adiosspandit @hsinghkalsi
